config/routes.rb
Rails.application.routes.draw do
 
  
  
 

 

  

 devise_for :users

 
 resources :users do
   resources :businesses
   resources :tax_returns do
     get 'user_interview/show'
     get 's_corp_k1/show'
     get 's_corp/show'
   end
 end
 
 resources :connect do
  collection do
    get :authenticate
    get :oauth_callback
  end
 
  
 end

root 'dashboard#index'
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 

end

app/models/business.rb
class Business < ActiveRecord::Base
  
  belongs_to :user
  has_one :tax_return

end

app/models/tax_return.rb
class TaxReturn < ActiveRecord::Base
  belongs_to :user
  belongs_to :business
  
  validates :business_id, uniqueness: true
  
  def current_business
    Business.find(self.business_id)
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :businesses
  has_many :tax_returns

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  


end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_filter :load_user
  
  before_action :show, only: [:show, :edit, :update, :destroy]
  
  

  # GET /businesses
  # GET /businesses.json
  def index
    @businesses = @user.businesses.all
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
    @business = @user.businesses.find(params[:id])
    
  end

  # GET /businesses/new
  def new
    @business = @user.businesses.new
  end

  # GET /businesses/1/edit
  def edit
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = @user.businesses.build(business_params)

    respond_to do |format|
      if @business.save
        format.html { redirect_to root_path(@user), notice: 'Business was successfully created.' }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    @business = @user.businesses.find(params[:id])
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to edit_user_business_path(@user, @business), notice: 'Business was successfully updated.' }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business = @user.businesses.find(params[:id])
    
    @business.destroy
    respond_to do |format|
      format.html { redirect_to root_path(@user), notice: 'Business was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
   
    # Never trust parameters from the scary internet, only allow the white list through.
   def business_params
    params.require(:business).permit(:business_name, :business_start, :business_street_1, :business_street_2, :business_city, :business_state, :business_zip, :ein, :biz_type, :bac, :method, :activity, :product, :schb3, :schb4a, :schb4b, :schb10a, :schb10b, :gross_receipts, :returns, :cost_goods, :other_income, :off_comp, :salaries, :repairs, :bad_debt, :rents, :taxes, :interest, :depreciations, :advertising, :pension, :emp_ben, :other_deductions, :accounting, :auto, :bank_charge, :cell_phone, :commissions, :computer, :consulting, :credit_costs, :delivery, :dues, :education, :fuel, :gifts, :ind_contractor, :insurance, :internet, :janitorial, :legal_professional, :marketing, :meals50, :misc, :office, :parking, :payroll_process, :permits, :postage, :printing, :software, :supplies, :telephone, :tools, :travel, :utilities, :waste_removal, :other1, :other2, :other3, :other4, :other5, :other6)
   end
    
    def load_user
      @user = User.find(params[:user_id])
    end
end

app/controllers/connect_controller.rb
class ConnectController < ApplicationController

  def index
  end
  
  def show
  end
  
  def authenticate
    callback = oauth_callback_connect_index_url
    token = QB_OAUTH_CONSUMER.get_request_token(:oauth_callback => callback)
    session[:qb_request_token] = Marshal.dump(token)
    redirect_to("https://appcenter.intuit.com/Connect/Begin?oauth_token=#{token.token}") and return
  end
  
  def oauth_callback
    Marshal.load(session[:qb_request_token]).get_access_token(:oauth_verifier => params[:oauth_verifier])
    token = @token
    secret = @secret
    realm_id = params['realmId']
    flash.notice = "Your QuickBooks account has been successfully linked."
    @msg = 'Redirecting. Please wait'
    @url = connect_index_path
    render 'close_and_redirect', layout: false
    # store the token, secret & RealmID somewhere for this user, you will need all 3 to work with Quickbooks-Ruby
end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
  end








end

app/controllers/pdfs_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    respond_to do |format|
      format.pdf { send_file TestPdfForm.new(user).export, type: 'application/pdf' }
    end
  end
end

app/controllers/s_corp_controller.rb
class SCorpController < ApplicationController
   before_filter :load_user
  
  
  
  
  def show
   
    render :layout => "s_corp"
  end






  private

  def load_user
      @user = User.find(params[:user_id])
      @tax_return = TaxReturn.find(params[:tax_return_id])
  end

end

app/controllers/s_corp_k1_controller.rb
class SCorpK1Controller < ApplicationController
before_filter :load_user
  
  
  
  
  def show
   
    render :layout => "s_corp_k1"
  end






  private

  def load_user
      @user = User.find(params[:user_id])
      @tax_return = TaxReturn.find(params[:tax_return_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :set_user, only: [:show, :edit, :update, :destroy] 

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
   
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user_name, :user_email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/business_summary_helper.rb
module BusinessSummaryHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/connect_helper.rb
module ConnectHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/return_wizard_helper.rb
module ReturnWizardHelper
end

app/helpers/returns_helper.rb
module ReturnsHelper
end

app/helpers/s_corp_helper.rb
module SCorpHelper
end

app/helpers/s_corp_k_1_helper.rb
module SCorpK1Helper
end

app/helpers/user_interview_helper.rb
module UserInterviewHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/businesses/_form.html.erb
<div>
<!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#" data-target="#contact" aria-controls="contact" role="tab" data-toggle="tab">Contact Information</a></li>
    <li role="presentation"><a href="#" data-target="#profile" aria-controls="profile" role="tab" data-toggle="tab">Business Settings</a></li>
    <li role="presentation"><a href="#" data-target="#messages" aria-controls="messages" role="tab" data-toggle="tab">Income</a></li>
    <li role="presentation"><a href="#" data-target="#settings" aria-controls="settings" role="tab" data-toggle="tab">Deductions</a></li>
     <li role="presentation"><a href="#" data-target="#other_exp" aria-controls="other_exp" role="tab" data-toggle="tab">Other Deductions</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="contact">
      <%= simple_form_for [@user, @business] do |f| %>
      <%= f.error_notification %>
      <div class="content-div">
        <div class="form-inputs">
          
          <%= f.input :business_name %>
          <div class="col-md-6">
          <%= f.input :business_street_1 %>
          <%= f.input :business_city %>
          <%= f.input :business_state, label: "State", :input_html => {:maxlength =>2, :style=> 'width: 60px'} %>
          <%= f.input :business_zip, label: "Zip Code", :input_html => {:maxlength =>5, :style=> 'width: 120px'} %>
          </div>
          <div class="col-md-6">
          <%= f.input :business_street_2 %>
          <%= f.input :ein, label: "EIN" %>  
          <%= f.input :business_start, label: "Business Start Date", :order => [:month, :day, :year] %>
          <%= f.input :biz_type, label: "Business Type", collection: ['S-corp', 'Partnership'] %>
          </div>
        </div>
  
        <div class="form-actions" class: "btn btn-primary">
        <%= f.button :submit, 'Save', :class => "btn btn-primary" %>
        </div>
      </div>
      <% end %>
    </div>
    <div role="tabpanel" class="tab-pane" id="profile">
      <%= simple_form_for [@user, @business] do |f| %>
      <%= f.error_notification %>
      <div class="content-div">
        <div class="form-inputs">
          <div class="row">
            <div class="col-md-6">
            <%= f.input :bac, label: "Business Activity Code", :input_html => {:maxlength =>5, :style=> 'width: 120px'} %>
            <%= f.input :method, label: "Accounting Method", collection: ['Cash Basis', 'Accrual Basis'], :input_html => {:style=> 'width: 220px'} %>
            <%= f.input :activity, label: "Business Activity" %>
            <%= f.input :product, label: "Business Product" %>
            <%= f.input :schb3, label: "Any shareholder a disregarded entity, estate, or trust?", collection: ['Yes', 'No'], :input_html => {:style=> 'width: 220px'} %>
            </div>
            <div class="col-md-6">
            <%= f.input :schb4a, label: "Does the business directly own 20% or more of the stock of any corporation?", collection: ['Yes', 'No'], :input_html => {:style=> 'width: 220px'} %>
            <%= f.input :schb4b, label: "Does the business directly own 20% or more of the stock of any partnership?", collection: ['Yes', 'No'], :input_html => {:style=> 'width: 220px'} %>
            <%= f.input :schb10a, label: "Were total receipts less than $250,000 for the year?", collection: ['Yes', 'No'], :input_html => {:style=> 'width: 220px'} %>
            <%= f.input :schb10b, label: "Were total assets less than $250,000 for the year?", collection: ['Yes', 'No'], :input_html => {:style=> 'width: 220px'} %>
            </div>
          </div>  
        </div>
  
        <div class="form-actions" class: "btn btn-primary">
        <%= f.button :submit, 'Save', :class => "btn btn-primary" %>
        </div>
      </div>
      <% end %>
    </div>
    <div role="tabpanel" class="tab-pane" id="messages">
      <%= simple_form_for [@user, @business] do |f| %>
      <%= f.error_notification %>
      <div class="content-div">
        <div class="form-inputs">
          <%= f.input :gross_receipts, label: "Gross Receipts or Sales", :input_html => {:style=> 'width: 220px'} %>
          <%= f.input :returns, :input_html => {:style=> 'width: 220px'} %>
          <%= f.input :cost_goods, label: "Cost of Goods Sold:", :input_html => {:style=> 'width: 220px'} %>
          <%= f.input :other_income, label: "Other Income", :input_html => {:style=> 'width: 220px'} %>
          
        </div>
  
        <div class="form-actions" class: "btn btn-primary">
        <%= f.button :submit, 'Save', :class => "btn btn-primary" %>
        </div>
      </div>
      <% end %>
    </div>
    <div role="tabpanel" class="tab-pane" id="settings">
      <%= simple_form_for [@user, @business] do |f| %>
      <%= f.error_notification %>
      <div class="content-div">
        <div class="form-inputs">
          <%= f.input :off_comp %>
          <%= f.input :salaries %>
          <%= f.input :repairs %>
          <%= f.input :bad_debt %>
          <%= f.input :rents %>
          <%= f.input :taxes %>
          <%= f.input :interest %>
          <%= f.input :depreciation %>
          <%= f.input :advertising %>
          <%= f.input :pension %>
          <%= f.input :emp_ben %>
          <%= f.input :other_deductions %>
        </div>
  
        <div class="form-actions" class: "btn btn-primary">
        <%= f.button :submit, 'Save', :class => "btn btn-primary" %>
        </div>
      </div>
      <% end %>
    </div>
     <div role="tabpanel" class="tab-pane" id="other_exp">
      <%= simple_form_for [@user, @business] do |f| %>
      <%= f.error_notification %>
      <div class="content-div">
        <div class="form-inputs">
          
          <div class="col-md-4">
          <%= f.input :accounting %>
          <%= f.input :auto %>
          <%= f.input :bank_charge %>
          <%= f.input :cell_phone %>
          <%= f.input :commissions %>
          <%= f.input :computer %>
          <%= f.input :consulting %>
          <%= f.input :credit_costs %>
          <%= f.input :delivery %>
          <%= f.input :dues %>
          <%= f.input :education %>
          <%= f.input :fuel %>
          <%= f.input :gifts %>
          </div>
          <div class="col-md-4">
          <%= f.input :ind_contractor %>
          <%= f.input :insurance %>
          <%= f.input :internet %>
          <%= f.input :janitorial %>
          <%= f.input :legal_professional %>
          <%= f.input :marketing %>
          <%= f.input :meals50 %>
          <%= f.input :misc %>
          <%= f.input :office %>
          <%= f.input :parking %>
          <%= f.input :payroll_process %>
          <%= f.input :permits %>
          <%= f.input :postage %>
          </div>
          <div class="col-md-4">
          <%= f.input :printing %>
          <%= f.input :software %>
          <%= f.input :supplies %>
          <%= f.input :telephone %>
          <%= f.input :tools %>
          <%= f.input :travel %>
          <%= f.input :utilities %>
          <%= f.input :waste_removal %>
          <%= f.input :other1 %>
          <%= f.input :other2 %>
          <%= f.input :other3 %>
          <%= f.input :other4 %>
          <%= f.input :other5 %>
          <%= f.input :other6 %>
          </div>
        </div>
  
        <div class="form-actions" class: "btn btn-primary">
        <%= f.button :submit, 'Save', :class => "btn btn-primary" %>
        </div>
      </div>
      <% end %>
    </div>
    
    
    
    
  </div>

</div>





<div>

  

app/views/businesses/edit.html.erb
<div class="content-div">
  <div class="well well-sm">
    <h2 class="text-center">Business Data Entry</h2>
  </div>
<%= link_to "Tax Return Summary", user_tax_return_path(current_user, TaxReturn.where(business: @business).pluck(:id)), method: :get, class: "btn btn-primary pull-right" %>
<%= render 'form' %>


</div>

app/views/businesses/index.html.erb
<p id="notice"><%= notice %></p>

<div class="content-div">
  <div class="well well-sm">
    <h2 class="text-center">Business Entities</h2>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th>Business Name</th>
        <th>Street Address</th>
        <th>Street Address #2</th>
        <th>City</th>
        <th>State</th>
        <th>Zip</th>
      </tr>
    </thead>

  <tbody>
    <% @businesses.each do |business| %>
      <tr>
        <td><%= business.business_name %></td>
        <td><%= business.business_street_1 %></td>
        <td><%= business.business_street_2 %></td>
        <td><%= business.business_city %></td>
        <td><%= business.business_state %></td>
        <td><%= business.business_zip %></td>
        <td><%= link_to 'Show', user_business_path(@user, business) %></td>
        <td><%= link_to 'Edit', edit_user_business_path(@user, business) %></td>
        <td><%= link_to 'Destroy', [@user, business], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Business', new_user_business_path %>

</div>

app/views/businesses/new.html.erb
<div class="content-div">
  <div class="well well-sm">
    <h2 class="text-center">New Business</h2>
  </div>

<%= render 'form' %>

<%= link_to 'Back', user_businesses_path %>
</div>

app/views/businesses/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_business_path(@user, @business) %> |
<%= link_to 'Back', user_businesses_path(@user) %>

app/views/connect/close_and_redirect.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @msg %></title>
</head>
<body>
<h3><%= @msg %></h3>

<script>
 setTimeout(function(){ window.opener.location = '<%= @url %>'; window.close(); }, 10000);
</script>
</body>
</html>

app/views/connect/index.html.erb
<body>
  <div class="content-div">
    <% unless session[:token] %>
      <ipp:connectToIntuit></ipp:connectToIntuit>
    <% end %>

    <% if notice %>
      <div style="padding: 10px;background: gainsboro;font-weight: 900;width: 50%;"><%= notice %></div>
    <% end %>
    
    
     
  </div>
 
  <script type="text/javascript" src="https://appcenter.intuit.com/Content/IA/intuit.ipp.anywhere.js"></script>
  <script>intuit.ipp.anywhere.setup({menuProxy: '/path/to/blue-dot', grantUrl: '<%= authenticate_connect_index_url %>'}); </script>
 
</body>
 
 
  
  
  
    
  

  

app/views/connect/show.html.erb
Connect Show

app/views/dashboard/index.html.erb
<% user_signed_in? %>
<div class="row">
  <div class="content-div">
    <div class="well well-sm">
      <h2 class="text-center">Dashboard</h2>
    </div>
    <%= link_to 'New Business', new_user_business_path(current_user), class: "btn btn-default pull-right" %>
  </div>
</div>
<div class="row">
  <div class="content-div">
    <table class="table">
      <thead>  
        <tr>
          <th>Business Name</th>
          <th>EIN</th>
          <th>Business Type</th>
        </tr>
      </thead>
      <tbody>
        <tr>
        <% User.find(current_user.id).businesses.each do |biz| %>
          <td><%= link_to biz.business_name, edit_user_business_path(current_user, biz) %></td>
          <td><%= biz.ein %></td>
          <td><%= biz.biz_type %></td>
          <td><%= link_to "Edit", edit_user_business_path(current_user, biz), class: "btn btn-success" %></td>
          <td><%= link_to "Delete", [current_user, biz], class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure?"} %></td>
          <td><%= link_to "Start Return", user_tax_return_user_interview_show_path(current_user, 2), class: "btn btn-primary" %></td>
          
        </tr>
        <% end %>
      </tbody>
    </table>
    
  </div>
</div>

app/views/s_corp/_pg5.html.erb
<body>
	<div class="wholepage">
		<div class="pagewrapper">
			<div class="hpageinfo clearfix bdr-bottom">
				<p class="pull-left">Form 1120S(2015)</p>
				<p class="pull-right">Page <span>5</span></p>
			</div>
			<div class="form-content">
				<form>
					<div class="forcalender clearfix bdr-bottom schedulem1 ">
						<span class="Schedulename">Schedule M-1 </span><b>Reconciliation of Income (Loss) per Books With Income (Loss) per Return <br>Note:</b> The corporation may be required to file Schedule M-3 (see instructions)
					</div>
				</form>
			</div>
			<div class="shedulem1-content bdr-bottom">
				<div class="clearfix"> 
					<div class="halfdiv bdr-right">
						<ul class="sheduleb-list">
							<li>
								<span class="numbli">1</span>
								<div class="shedulem-s">
									Net income (loss) per books . . . . . . . . . . 
									<div class="box-right">
										<div class="box-file fullb"></div>
									</div>
								</div>
							</li>
							<li>
								<span class="numbli">2</span>
								<div class="shedulem-s">
									Income included on Schedule K, lines 1, 2, 3c, 4, 5a, 6, 7, 8a, 9, and 10, not recorded on books this year (itemize) <span class="space-20"></span> <div class="box-file box-150"></div>
									<div class="box-right">
										<div class="box-file fullb"></div>
									</div>
								</div>
							</li>
							<li>
								<span class="numbli">3</span>
								<div class="shedulem-s">
									Expenses recorded on books this year not<br> included on Schedule K, lines 1 through 12 and 14l (itemize): 
								</div>
								<ul>
									<li>
										<div class="shedulem-s">
											Depreciation $ <div class="box-file pull-right box-160"></div>
											<div class="clearfix"></div>
										</div>
									</li>
									<li>
										<div class="shedulem-s">
											Travel and entertainment $ <div class="box-file pull-right box-100"></div>
											<div class="clearfix"></div>
										</div>
									</li>
									<li>
										<div class="shedulem-s">
											<div class="box-file binline fullb"></div>
											<div class="clearfix"></div>
											<div class="box-right">
												<div class="box-file fullb"></div>
											</div>

										</div>
									</li>
								</ul>
							</li>
							<li>
								<span class="numbli">4</span>
								<div class="shedulem-s">
									Add lines 1 through 3 
									<div class="box-right">
										<div class="box-file fullb"></div>
									</div>
								</div>
							</li>
						</ul>
					</div>
					<div class="halfdiv">
						<ul class="sheduleb-list">
							<li>
								<span class="numbli">5</span>
								<div class="shedulem-s">
									Income recorded on books this year not included on Schedule K, lines 1 through 10 (itemize): 
								</div>
								<ul>
									<li>
										<div class="shedulem-s">
											Tax-exempt interest $ <div class="box-file pull-right box-100"></div>
											<div class="box-file binline fullb"></div>
											<div class="clearfix"></div>

											<div class="box-right">
												<div class="box-file fullb"></div>
											</div>
										</div>
									</li>
								</ul>
							</li>
							<li>
								<span class="numbli">6</span>
								<div class="shedulem-s">
									Deductions included on Schedule K, lines 1 through 12 and 14l, not charged against book income this year (itemize):
									<div class="box-right">
										<div class="box-file fullb"></div>
									</div>
								</div>
								<ul>
									<li>
										<div class="shedulem-s">
											Depreciation $ <div class="box-file pull-right box-100"></div>
											<div class="box-file binline fullb"></div>
											<div class="clearfix"></div>

											<div class="box-right">
												<div class="box-file fullb"></div>
											</div>
										</div>
									</li>
								</ul>
							</li>
							<li>
								<span class="numbli">7</span>
								<div class="shedulem-s">
									Add lines 5 and 6 . . . . .
									<div class="box-right">
										<div class="box-file fullb"></div>
									</div>
								</div>
							</li>
							<li>
								<span class="numbli">8</span>
								<div class="shedulem-s">
									<span class="font-10">Income (loss) (Schedule K, line 18). Line 4 less line 7</span>
									<div class="box-right">
										<div class="box-file fullb"></div>
									</div>
								</div>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="forcalender clearfix bdr-bottom schedulem1 ">
				<span class="Schedulename">Schedule M-2 </span><b>Analysis of Accumulated Adjustments Account, Other Adjustments Account, and Shareholders’ <br>Undistributed Taxable Income Previously Taxed</b> (see instructions)
			</div>
			<table class="m2table">
				<tr>
					<td>
						
					</td>
					<td>
						<b>(a)</b> Accumulated <br> adjustments account
					</td>
					<td>
						<b>(b)</b> Other adjustments <br>account 
					</td>
					<td>
						<b>(c)</b> Shareholders’ undistributed <br> taxable income previously taxed
					</td>

				</tr>
				<tr>
					<td><span class="space-20">1</span> Balance at beginning of tax year <span class="dottedline"></span></td>
					<td><div class="box-file fullb"></div></td>
					<td><div class="box-file fullb"></div></td>
					<td><div class="box-file fullb"></div></td>
				</tr>
				<tr>
					<td><span class="space-20">2</span> Ordinary income from page 1, line 21 <span class="dottedline"></span></td>
					<td><div class="box-file fullb"></div></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td><span class="space-20">3</span>Other additions <span class="dottedline"></span></td>
					<td><div class="box-file fullb"></div></td>
					<td><div class="box-file fullb"></div></td>
					<td></td>
				</tr>
				<tr>
					<td><span class="space-20">4</span>Loss from page 1, line 21 <span class="dottedline"></span></td>
					<td><div class="box-file fullb"></div></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td><span class="space-20">5</span>Other reductions <span class="dottedline"></span></td>
					<td><div class="box-file fullb after-before"></div></td>
					<td><div class="box-file fullb"></div></td>
					<td></td>
				</tr>
				<tr>
					<td><span class="space-20">6</span>Combine lines 1 through 5 <span class="dottedline"></span></td>
					<td><div class="box-file fullb after-before"></div></td>
					<td><div class="box-file fullb after-before"></div></td>
					<td><div class="box-file fullb"></div></td>
				</tr>
				<tr>
					<td><span class="space-20">7</span>Distributions other than dividend distributions <span class="dottedline"></span></td>
					<td><div class="box-file fullb"></div></td>
					<td><div class="box-file fullb"></div></td>
					<td><div class="box-file fullb"></div></td>
				</tr>
				<tr>
					<td><span class="space-20">8</span>Balance at end of tax year. Subtract line 7 from line 6 </td>
					<td><div class="box-file fullb"></div></td>
					<td><div class="box-file fullb"></div></td>
					<td><div class="box-file fullb"></div></td>
				</tr>
			</table>
			<div class="hpageinfo clearfix bdr-top">
				<p class="pull-right">From <span> 1120S </span> (2015)</p>

			</div>
		</div>
	</div>
</body>