config/routes.rb
Rails.application.routes.draw do
 
  
  
 

 

  

 devise_for :users

 
 resources :users do
   resources :businesses
   resources :tax_returns do
     get 'user_interview/show'
     get 's_corp_k1/show'
     get 's_corp/show'
   end
 end
 
 resources :connect do
  collection do
    get :authenticate
    get :oauth_callback
  end
 
  
 end

root 'dashboard#index'
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 

end

app/models/tax_return.rb
class TaxReturn < ActiveRecord::Base
  belongs_to :user
  belongs_to :business
  
  validates :business_id, uniqueness: true
  
  def current_business
    Business.find(self.business_id)
  end
  
end

app/controllers/tax_returns_controller.rb
class TaxReturnsController < ApplicationController
  before_filter :load_user
  
  
  def intitialize
    @tax_return = tax_return
  end
  
  def index
   @tax_returns = @user.tax_returns.all
  end

  def show
    @tax_return = @user.tax_returns.find(params[:id])
   
    
  
  end
  
  def new
    @tax_return = @user.tax_returns.new
  end
  
  def create
    @tax_return = @user.tax_returns.build(tax_return_params)
    
    if @tax_return.save
      redirect_to user_tax_returns_path
    else
      render 'new'
    end
  end
  
  def update
    @tax_return = @user.tax_returns.find(params[:id])
    respond_to do |format|
      if @tax_return.update(tax_return_params)
        format.html { redirect_to edit_user_tax_return_path(@user, @tax_return), notice: 'Return was successfully updated.' }
        format.json { render :show, status: :ok, location: @tax_return }
      else
        format.html { render :edit }
        format.json { render json: @tax_return.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
  @tax_return = @user.tax_returns.find(params[:id])
  
  @tax_return.destroy
    respond_to do |format|
      format.html { redirect_to user_tax_returns_path(@user), notice: 'Tax Return was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  
  private
  
  def tax_return_params
    params.require(:tax_return).permit(:business_id)
  end
  
  def load_user
      @user = User.find(params[:user_id])
  end
  
end

app/views/tax_returns/_form.html.erb
<%= simple_form_for [@user, @tax_return] do |f| %>
<%= f.error_notification %>

<%= f.association :business, collection: Business.where(user_id: @user), label_method: :business_name %>

<%= f.button :submit %>
<% end %>

app/views/tax_returns/index.html.erb
<div class="row">
  <div class="content-div">
    <div class="well well-sm">
      <h2 class="text-center">Tax Returns</h2>
    </div>
    <%= link_to 'New Return', new_user_tax_return_path(current_user), class: "btn btn-default pull-right" %>
  </div>
</div>
<% if flash[:notice] %>
    <div id="notice"><%= flash[:notice] %></div>
<% end %>


<div class="content-div">
  <table class="table">
    <thead>
      <tr>
        <th>Return Name</th>
        <th>Business EIN</th>
        <th>Business ID</th>
      </tr>
    </thead>
    <tbody>
      <% @tax_returns.each do |taxrtn| %>
      <tr>
        <td><%= link_to Business.find(taxrtn.business_id).business_name, user_tax_return_path(@user, taxrtn.id)  %> </td>
        <td><%= Business.find(taxrtn.business_id).ein %></td>
        <td><%= taxrtn.business_id %></td>
        <td><%= link_to 'Delete Return', [@user, taxrtn], class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tax_returns/new.html.erb
<div class="content-div">
  <div class="well well-sm">
    <h2 class="text-center">New Tax Return</h2>
  </div>

<%= render 'form' %>

</div>

app/views/tax_returns/show.html.erb
<div class="content-div">
  <div class="well well-sm">
    <h2 class="text-center"><%= Business.find(@tax_return.business_id).business_name %> Tax Return</h2>
  </div>
  <%= link_to 'S-corp Return', user_tax_return_s_corp_show_path(current_user, @tax_return), method: :get, class: "btn btn-default" %>
  <%= link_to 'S-corp K-1', user_tax_return_s_corp_k1_show_path(current_user, @tax_return), method: :get, class: "btn btn-default" %>
</div>

app/views/tax_returns/summary.html.erb
<div class="content-div"> 
  <%= link_to "Return Data Entry", edit_user_business_path(current_user, @tax_return.business_id), class: "btn btn-default" %>
  <h3 class="text-center"><%= Business.find(@tax_return.business_id).business_name %></h3>
  <h3 class="text-center">Federal Tax Return Summary</h3>
  <hr>
  <h5 class="text-center">Tax Year 2016</h5>
  <div class="panel panel-default">
    <div class="panel-heading">Income</div>
    <table class="table">
      <colgroup>
        <col class="col-md-4">
        <col class="col-md-2">
      </colgroup>
      <thead>
        <tr>
          <th>Account Name</th>
          <th>Amount</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Gross Revenue</td>
          <td><%= number_to_currency(Business.find(@tax_return.business_id).gross_receipts) %></td>
        </tr>
        <tr>
          <td>Returns & Allowances</td>
          <td><%= number_to_currency(Business.find(@tax_return.business_id).returns) %></td>
        </tr>
        <tr>
          <td>Balance</td>
          <% bal = (Business.find(@tax_return.business_id).gross_receipts) - (Business.find(@tax_return.business_id).returns) %>
          <td><%= number_to_currency(bal) %></td>
        </tr>
        <tr>
          <td>Cost Of Goods Sold</td>
          <% cogs = (Business.find(@tax_return.business_id).cost_goods) %>
          <td><%= number_to_currency(cogs) %></td>
        </tr>
        <tr>
          <td>Other Income</td>
          <td><%= number_to_currency(Business.find(@tax_return.business_id).other_income) %></td>
        </tr>
        <tr>
          <td><strong>Total Income</strong></td>
          <td><strong><%= number_to_currency(bal - cogs + (Business.find(@tax_return.business_id).other_income)) %> </strong></td>
        </tr>
      </tbody>
    </table>
  </div>
  
  <!-- Deductions Section -->
  <div class="panel panel-default">
    <div class="panel-heading">Deductions</div>
    <table class="table">
       <colgroup>
        <col class="col-md-4">
        <col class="col-md-2">
      </colgroup>
      <thead>
        <tr>
          <th>Account Name</th>
          <th>Amount</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Compensation of Officers</td>
          <td><%= number_to_currency(Business.find(@tax_return.business_id).off_comp) %></td>
        </tr>
        <tr>
          <td>Salaries & Wages</td>
          <td><%= number_to_currency(Business.find(@tax_return.business_id).salaries) %></td>
        </tr>
        <tr>
          <td>Repairs & Maintenance</td>
          <td><%= number_to_currency(Business.find(@tax_return.business_id).repairs) %></td>
        </tr>
        <tr>
          <td>Bad Debts</td>
          <td><%= number_to_currency(Business.find(@tax_return.business_id).bad_debt) %></td>
        </tr>
        <tr>
          <td>Rents</td>
          <td><%= number_to_currency(Business.find(@tax_return.business_id).rents) %></td>
        </tr>
        <tr>
          <td>Taxes and Licenses</td>
          <td><%= number_to_currency(Business.find(@tax_return.business_id).taxes) %></td>
        </tr>
        <tr>
          <td>Interest</td>
          <td><%= number_to_currency(Business.find(@tax_return.business_id).interest) %></td>
        </tr>
        <tr>
          <td>Depreciation</td>
          <td><%= number_to_currency(Business.find(@tax_return.business_id).depreciation) %></td>
        </tr>
        <tr>
          <td>Advertising</td>
          <td><%= number_to_currency(Business.find(@tax_return.business_id).advertising) %></td>
        </tr>
        <tr>
          <td>Pension & Profit Sharing</td>
          <td><%= number_to_currency(Business.find(@tax_return.business_id).pension) %></td>
        </tr>
        <tr>
          <td>Employee Benefit Programs</td>
          <td><%= number_to_currency(Business.find(@tax_return.business_id).emp_ben) %></td>
        </tr>
        <tr>
          <td>Other Deductions</td>
          <td><%= number_to_currency(Business.find(@tax_return.business_id).other_deductions) %></td>
        </tr>
        <tr>
          <td><strong>Total Deductions</strong></td>
          <td><strong><%= number_to_currency(bal - cogs + (Business.find(@tax_return.business_id).other_income)) %> </strong></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>  
  