config/routes.rb
Rails.application.routes.draw do
 
  
  
 

 

  

 devise_for :users

 
 resources :users do
   resources :businesses
   resources :tax_returns do
     get 'user_interview/show'
     get 's_corp_k1/show'
     get 's_corp/show'
   end
 end
 
 resources :connect do
  collection do
    get :authenticate
    get :oauth_callback
  end
 
  
 end

root 'dashboard#index'
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 

end

app/models/business.rb
class Business < ActiveRecord::Base
  
  belongs_to :user
  has_one :tax_return

end

app/models/tax_return.rb
class TaxReturn < ActiveRecord::Base
  belongs_to :user
  belongs_to :business
  
  validates :business_id, uniqueness: true
  
  def current_business
    Business.find(self.business_id)
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :businesses
  has_many :tax_returns

end

app/controllers/connect_controller.rb
class ConnectController < ApplicationController

  def index
  end
  
  def show
  end
  
  def authenticate
    callback = oauth_callback_connect_index_url
    token = QB_OAUTH_CONSUMER.get_request_token(:oauth_callback => callback)
    session[:qb_request_token] = Marshal.dump(token)
    redirect_to("https://appcenter.intuit.com/Connect/Begin?oauth_token=#{token.token}") and return
  end
  
  def oauth_callback
    Marshal.load(session[:qb_request_token]).get_access_token(:oauth_verifier => params[:oauth_verifier])
    token = @token
    secret = @secret
    realm_id = params['realmId']
    flash.notice = "Your QuickBooks account has been successfully linked."
    @msg = 'Redirecting. Please wait'
    @url = connect_index_path
    render 'close_and_redirect', layout: false
    # store the token, secret & RealmID somewhere for this user, you will need all 3 to work with Quickbooks-Ruby
end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
  end








end

app/controllers/pdfs_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    respond_to do |format|
      format.pdf { send_file TestPdfForm.new(user).export, type: 'application/pdf' }
    end
  end
end

app/controllers/s_corp_controller.rb
class SCorpController < ApplicationController
   before_filter :load_user
  
  
  
  
  def show
   
    render :layout => "s_corp"
  end






  private

  def load_user
      @user = User.find(params[:user_id])
      @tax_return = TaxReturn.find(params[:tax_return_id])
  end

end

app/controllers/s_corp_k1_controller.rb
class SCorpK1Controller < ApplicationController
before_filter :load_user
  
  
  
  
  def show
   
    render :layout => "s_corp_k1"
  end






  private

  def load_user
      @user = User.find(params[:user_id])
      @tax_return = TaxReturn.find(params[:tax_return_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :set_user, only: [:show, :edit, :update, :destroy] 

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
   
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user_name, :user_email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/business_summary_helper.rb
module BusinessSummaryHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/connect_helper.rb
module ConnectHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/return_wizard_helper.rb
module ReturnWizardHelper
end

app/helpers/returns_helper.rb
module ReturnsHelper
end

app/helpers/s_corp_helper.rb
module SCorpHelper
end

app/helpers/s_corp_k_1_helper.rb
module SCorpK1Helper
end

app/helpers/user_interview_helper.rb
module UserInterviewHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html data-wf-page="57ad15e01fd32dc352aba806" data-wf-site="57ad15e01fd32dc352aba805">
<head>
  <meta charset="utf-8">
  <title>HALON Tax</title>
  <meta content="width=device-width, initial-scale=1" name="viewport">
  <meta content="Webflow" name="generator">
  <script src="https://code.jquery.com/jquery-3.1.0.slim.min.js" integrity="sha256-cRpWjoSOw5KcyIOaZNo4i6fZ9tKPhYYb6i5T9RSVJG8=" crossorigin="anonymous"></script>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  
  <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js"></script>
  <script type="text/javascript">
    WebFont.load({
      google: {
        families: ["Open Sans:300,300italic,400,400italic,600,600italic,700,700italic,800,800italic"]
      }
    });
  </script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track'=> true %>
  
  
  
  <link href="https://daks2k3a4ib2z.cloudfront.net/img/favicon.ico" rel="shortcut icon" type="image/x-icon">
  <link href="https://daks2k3a4ib2z.cloudfront.net/img/webclip.png" rel="apple-touch-icon">
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div class="nav-section">
    <div class="nav-div w-clearfix"><a class="nav-logo-link-block w-inline-block" href="#"><h3 class="nav-logo" >HALON</h3></a><%= link_to "Logout", destroy_user_session_path, :method => :delete, id: "navlink", class: "nav-link" %><a div id="navlink" class="nav-link" href="#">Help</a><a div id="navlink" class="nav-link" href="#">Vault</a><a div id="navlink" class="nav-link" href="#">Diagnostics</a><%= link_to "Tax Returns", user_tax_returns_path(current_user), id: "navlink", class: "nav-link" %><%= link_to "Dashboard", root_path, id: "navlink", class: "nav-link" %>
    </div>
  </div>
  
  <%= yield %>
  
  
  
  
  <!--[if lte IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif]-->
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>

<html data-wf-page="57ad15e01fd32dc352aba806" data-wf-site="57ad15e01fd32dc352aba805">
<head>
  <meta charset="utf-8">
  <title>HALON Tax</title>
  <meta content="width=device-width, initial-scale=1" name="viewport">
  <meta content="Webflow" name="generator">
  <script src="https://code.jquery.com/jquery-3.1.0.slim.min.js" integrity="sha256-cRpWjoSOw5KcyIOaZNo4i6fZ9tKPhYYb6i5T9RSVJG8=" crossorigin="anonymous"></script>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  
  <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js"></script>
  <script type="text/javascript">
    WebFont.load({
      google: {
        families: ["Open Sans:300,300italic,400,400italic,600,600italic,700,700italic,800,800italic"]
      }
    });
  </script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track'=> true %>
  
  
  
  <link href="https://daks2k3a4ib2z.cloudfront.net/img/favicon.ico" rel="shortcut icon" type="image/x-icon">
  <link href="https://daks2k3a4ib2z.cloudfront.net/img/webclip.png" rel="apple-touch-icon">
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div class="content-div">
    <div class="well well-purple" style="background-color: #7227a3">
      <h2 class="nav-logo text-center">HALON</h2>
    </div>
  </div>
   
   <%= yield %> 
    
 
  
  
  
</body>
</html>

app/views/layouts/return.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Form</title>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'form', 'data-turbolinks-track' => true %>
   
</head>
  <%= yield %>
</html>

app/views/layouts/s_corp.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>S Corp Return</title>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'form', 'data-turbolinks-track' => true %>
    
   
</head>
  <%= yield %>
</html>

app/views/layouts/s_corp_k1.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>S Corp K-1</title>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'k1style', 'data-turbolinks-track' => true %>
    
   
</head>
  <%= yield %>
</html>